### ISSUE TITLE
About README

### ISSUE THREAD

**Issue by Golden-Pigeon** [DarlingHang/deceptive-nerf#1]
Hi, @DarlingHang 

Thanks for your wonderful work on 3D reconstruction and this opensource repo.

In [README.md](https://github.com/DarlingHang/deceptive-nerf/blob/db010206d2aa8b69b0140e19527eb2d2f073c1c5/README.md?plain=1#L45), it says 

> If you find *ChatCam* useful in your research, please consider citing: 

I wonder if it would be Deceptive-NeRF/3DGS instead of ChatCam. It seems like [ChatCam](https://arxiv.org/abs/2409.17331v1) is anothor work of yours!

**Comment by DarlingHang** [comment]
Thanks @Golden-Pigeon! I am fixing this typo.
